### ISSUE TITLE
Incorrect import causes MagTag to freeze

### ISSUE THREAD

**Issue by leadmocha** [adafruit/Adafruit_CircuitPython_MagTag#43] opened 2020-12-15 23:12 UTC
Hi, not sure if this is a CircuitPython bug or a library bug, but on my MagTag running CircuitPython 6.1.0beta2 the following line causes the MagTag to stop responding when I have it plugged into the computer.

The issue happens both in the REPL and in code.py.  If I connect via minicom, then Ctrl+C to enter the REPL, then type:

```from adafruit_magtag.magtag import Graphics```

minicom stops responding, and shortly after the CIRCUITPY drive stops responding also. On one or two occasions I noticed that if I wait long enough (longer than half hour) minicom might start responding again, though, freezes instantly once I try to import it.    That could only be a coincidence, however, as it usually just freezes and rarely returns unless I turn off the MagTag and turn it on again.

I am using the latest library on circuitpython from today.

**Comment by makermelissa** [comment] 2020-12-16 00:52
Please try using
```
from adafruit_magtag.graphics import Graphics
```

**Comment by makermelissa** [comment] 2020-12-16 01:03
I changed the title because it should give an error message rather than freeze.

**Comment by leadmocha** [comment] 2020-12-16 01:09
Thanks Melissa,

Okay, that worked, but now it just freezes on the next line which I changed from

```from adafruit_magtag.magtag import Network```

to

```from adafruit_magtag.network import Network```

Is this the wrong way to import Network?

**Comment by leadmocha** [comment] 2020-12-18 00:10
I just tried the latest circuitpython build from today and neither of these freeze my magtag:

```from adafruit_magtag.network import Network```

nor

```import wifi```

not even the incorrect form

```from adafruit_magtag.magtag import Graphics```

freezes my MagTag.  Though, no error message is produced in the last one. Should it have stilled produced an error message?

**Comment by makermelissa** [comment] 2020-12-19 00:12
I realize it didn't produce an error message because Graphics is imported inside of the magtag class, so it was successfully just re-imported from there, which means it would have likely worked. I tested this with using the import it to successfully change the background. 

It sounds like the issue is resolved, so I'm going to close this. If that's not the case, feel free to re-open.

**Closed by makermelissa** 2020-12-19 00:12 UTC
