### ISSUE TITLE
MAGTAG NEOPIXEL fails with 7.0

### ISSUE THREAD

**Issue by jerryneedell** [adafruit/Adafruit_CircuitPython_MagTag#62] opened 2021-06-02 14:42 UTC
With the current tip of main I get an error trying to use the magtag library
h was trying to run the "vaccine example"  https://learn.adafruit.com/adafruit-magtag-covid-vaccination-percent-tracker/code-the-vaccination-tracker
```
Press any key to enter the REPL. Use CTRL-D to reload.

Adafruit CircuitPython 7.0.0-alpha.2-736-gb49ee62af on 2021-06-02; Adafruit MagTag with ESP32S2
>>> import vaccine
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "vaccine.py", line 9, in <module>
  File "adafruit_magtag/magtag.py", line 102, in __init__
  File "adafruit_magtag/peripherals.py", line 47, in __init__
ValueError: NEOPIXEL_POWER_INVERTED in use
>>> 
```
 It runs fine on 6.3.0

**Comment by dherrada** [comment] 2021-06-02 14:53
_possibly_ (but probably not) related https://forums.adafruit.com/viewtopic.php?f=60&t=179248&p=872565#p872565

**Comment by tannewt** [comment] 2021-06-02 15:22
This might be related to the internal status LED rework. I looked in the code and it works OK though. Does the sample code work ok as `code.py`?

**Comment by jerryneedell** [comment] 2021-06-02 16:48
> This might be related to the internal status LED rework. I looked in the code and it works OK though. Does the sample code work ok as `code.py`?

No -same failure

**Comment by jerryneedell** [comment] 2021-06-02 17:18
It appears to be getting set here in neopixel.py https://github.com/adafruit/Adafruit_CircuitPython_NeoPixel/blob/a8e9975b3f06d454f8951254d96f99755b11d962/neopixel.py#L115 in CP 7

**Comment by makermelissa** [comment] 2021-06-02 17:44
Line 47 is just initializing the the pin to enable/disable the neopixels. This is used for power savings by allowing the users' code to disable the neopixels. It's possible this is due to the internal status rework if the NEOPIXEL_POWER pin is in use. Also, did it get renamed to NEOPIXEL_POWER_INVERTED in CP7?

**Comment by jerryneedell** [comment] 2021-06-02 18:33
in neopixel.py for CP 7 it configures the power pin -- so I think lines 47-47 of peripherals ar no longer needed (with CP 7)

**Comment by makermelissa** [comment] 2021-06-02 20:15
Ok yeah, maybe we can detect something and only run this on pre-7 versions.

**Comment by pjockey** [comment] 2021-07-16 02:12
Inquiring whether there has been any update on this thread?

**Comment by makermelissa** [comment] 2021-07-16 15:45
Not as far as I know, unless something was fixed in the core. Do you want to give it a try with the latest CircuitPython 7? Otherwise, I can probably get to this soon.

**Comment by dglaude** [comment] 2021-07-16 17:19
I can confirm the error with the latest library bundle from 20210716 and latest core:
`Adafruit CircuitPython 7.0.0-alpha.4-67-ge3bc800bb on 2021-07-14; Adafruit MagTag with ESP32S2
`

> Auto-reload is on. Simply save files over USB to run them or enter REPL to disable.
> code.py output:
> Traceback (most recent call last):
>   File "code.py", line 10, in <module>
>   File "adafruit_magtag/magtag.py", line 102, in __init__
>   File "adafruit_magtag/peripherals.py", line 47, in __init__
> ValueError: NEOPIXEL_POWER_INVERTED in use

**Comment by makermelissa** [comment] 2021-07-16 17:33
Thank you :)

**Comment by pjockey** [comment] 2021-07-16 23:46
Thanks.  Getting the exact same error. CP 6.3 works great.

**Closed** 2021-07-19 16:01 UTC

**Comment by dglaude** [comment] 2021-07-19 18:50
I took my attempt from 3 days ago , and replaced the magtag library with adafruit-circuitpython-magtag-7.x-mpy-2.1.1.zip from #63

But now my MagTag is rebooting in loop somewhere in
`magtag.network.connect()`

The only thing it say (except for print("**") deis

> Connecting to AP NEO

Where NEO is my SSID.

I will try to investigate further. But any news of someone making COVID percentage demo work (or failing like for me) would be welcomed.
